### ISSUE TITLE
It'd be useful to be able to specify Period and/or EvaluationPeriods

### ISSUE THREAD

**Issue by yashafromrussia** [sbstjn/serverless-sqs-alarms-plugin#7]
Proposed syntax:

```yml
custom:
  sqs-alarms:
    - queue: your-sqs-queue-name
      topic: your-sns-topic-name
      name: your-alarm-name # optional parameter
      thresholds:
        - value: 1
          period: 60
          evaluationPeriods: 5
```

But this looks like it would be a breaking change... So maybe being able to set Period and/or EvaluationPeriods just once for all thresholds is enough?

```yml
custom:
  sqs-alarms:
    - queue: your-sqs-queue-name
      topic: your-sns-topic-name
      name: your-alarm-name # optional parameter
      thresholds:
        - 1
      period: 60
      evaluationPeriods: 5
```

**Comment by sbstjn** [comment]
Good point 👍

Avoiding a breaking change in the API would be great. But I see no problem in supporting 

```yaml
thresholds:
  - value: 1
    period: 60
    evaluationPeriods: 5
```

as well as 

```yaml
thresholds:
  - 1
  - 2
```

However, I'm totally fine with the current features of the plugin. So you will have to implement in on your own, but I'm fine with merging a PR with those features!
